### ISSUE TITLE
make fails to compile

### ISSUE THREAD

**Issue by TahirMars** [Velocidex/velociraptor#2558]
OS
Ubuntu 22.04 LTS 

Version
v0.6.8

Go Version
go version go1.20.2 

Go Path
/usr/local/go

Trying to build velociraptor on Ubuntu 22.04 LTS  with make I get the following error:

![image](https://user-images.githubusercontent.com/26303398/226248901-ea51c1e5-4699-4fb4-93da-ad9fde647f32.png)

I tried to change to other versions of Golang (>=1.17), but also reported the same error, This seems to be a golang framework issue?

```
# make
go run make.go -v autoDev
Running target: AutoDev
exec: fileb0x crypto/b0x.yaml
exec: go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6
# net
/usr/local/go/src/net/dnsclient_unix.go:553:14: undefined: lookupStaticHost
/usr/local/go/src/net/dnsclient_unix.go:575:21: undefined: lookupStaticHost
/usr/local/go/src/net/dnsclient_unix.go:818:11: undefined: lookupStaticAddr
Error: running "go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6" failed with exit code 1
exit status 1
make: *** [Makefile:2：all] error 1
```

**Comment by scudette** [comment]
We build the entire project in every commit. Take a look at the github action build output (It currently builds with Go 1.20).

Generally it is not a good idea to build as root. Maybe this is the issue you are seeing?

**Comment by TahirMars** [comment]
The same error occurs when compiling with a non-root user（go version 1.20）
```
dfir@localhost:/root/dfir_platform$ go version
go version go1.20 linux/amd64
dfir@localhost:/root/dfir_platform$ sudo make
go run make.go -v autoDev
Running target: AutoDev
exec: fileb0x artifacts/b0x.yaml
exec: go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6
# net
/usr/local/go/src/net/dnsclient_unix.go:553:14: undefined: lookupStaticHost
/usr/local/go/src/net/dnsclient_unix.go:575:21: undefined: lookupStaticHost
/usr/local/go/src/net/dnsclient_unix.go:818:11: undefined: lookupStaticAddr
Error: running "go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6" failed with exit code 1
exit status 1
make: *** [Makefile:2：all] error 1
```

**Comment by scudette** [comment]
you are still compiling as root with sudo

**Comment by TahirMars** [comment]
so sad
```
dfir@localhost:$ make
go run make.go -v autoDev
Running target: AutoDev
exec: fileb0x artifacts/b0x.yaml
exec: go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6
# net
../go/src/net/dnsclient_unix.go:553:14: undefined: lookupStaticHost
../go/src/net/dnsclient_unix.go:575:21: undefined: lookupStaticHost
../go/src/net/dnsclient_unix.go:818:11: undefined: lookupStaticAddr
Error: running "go install github.com/Velocidex/fileb0x@d54f4040016051dd9657ce04d0ae6f31eab99bc6" failed with exit code 1
exit status 1
make: *** [Makefile:2：all] error 1
```
