### ISSUE TITLE
Release branches won't build with go1.27

### ISSUE THREAD

**Issue by djoreilly** [Velocidex/velociraptor#5019]
The v0.76-release and v0.77-release branches won't build with go1.27. The reason is discussed [here](https://github.com/golang/go/issues/78779#issuecomment-5012119796).

```bash
~/dev/gits/velociraptor v0.77-release ❯ go version
go version go1.27.1 linux/amd64

~/dev/gits/velociraptor v0.77-release ❯ make linux_bare
...
# github.com/go-json-experiment/json
/home/doreilly/go/pkg/mod/github.com/go-json-experiment/json@v0.0.0-20250910080747-cc2cfa0554c3/alias.go:618:21: undefined: json.SkipFunc
/home/doreilly/go/pkg/mod/github.com/go-json-experiment/json@v0.0.0-20250910080747-cc2cfa0554c3/alias.go:980:14: undefined: json.DiscardUnknownMembers
Error: running "go build -o output/velociraptor-v0.77.2-linux-amd64 -tags  server_vql extras disable_grpc_modules  release yara disable_gui  -ldflags= -w -s  -X "www.velocidex.com/golang/velociraptor/config.build_time=2026-09-16T18:57:19+01:00" -X "www.velocidex.com/golang/velociraptor/config.commit_hash=c0c9dd609" ./bin/" failed with exit code 1
exit status 1
make: *** [Makefile:68: linux_bare] Error 1
```

Will the github.com/go-json-experiment/json dependency be updated?

**Comment by scudette** [comment]
It looks like it is possible to switch back to the old json implementation using GOEXPERIMENT=nojsonv2 environment.

Currently the major breaks are:
https://github.com/go-language-server/protocol
github.com/kaptinlin/jsonschema

**Comment by scudette** [comment]
This is a temporary fix until the upstream deps can fix it
```diff
diff --git a/magefile.go b/magefile.go
index f416aa9f9..bacc79cba 100644
--- a/magefile.go
+++ b/magefile.go
@@ -68,7 +68,7 @@ var (
        // google cloud suddenly increased its dependency size by about
        // 20mb without warning. This little documented tag is used to
        // remove useless bloat.
-       base_tags = " server_vql extras disable_grpc_modules "
+       base_tags = " server_vql extras disable_grpc_modules goexperiment.nojsonv2 "

        // Where we store the toolchains and package caches
        toolchain_dir     = "./build/toolchain"
```

**Comment by djoreilly** [comment]
Thanks.
